version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.17-alpine
    working_directory: /go/src/gostradamus
    steps:
      - checkout
      - run: go install github.com/bykof/gostradamus

  lint:
    docker:
      - image: golangci/golangci-lint:v1.43-alpine
    steps:
      - checkout
      - run: golangci-lint run

  test:
    docker:
      - image: golang:1.17
    working_directory: /go/src/gostradamus
    steps:
      - checkout
      - run: go test -v -race -cover -coverprofile coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - lint
      - test