version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.14-alpine
    working_directory: /go/src/gostradamus
      - checkout
      - go install github.com/bykof/gostradamus

  lint:
    docker:
      - image: golangci/golangci-lint:v1.23-alpine
    steps:
      - checkout
      - run: golangci-lint run
  test:
    docker:
      - image: golang:1.14
    working_directory: /go/src/gostradamus
    steps:
      - checkout
      - run: go test -v -race ./...

workflows:
  build_lint_test:
    jobs:
      - build
      - lint
      - test